/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajeshwari
 */
public class Billing extends javax.swing.JFrame {
   private static DefaultTableModel model ;
   private static String cust_name=null;
   private static int si=0;
   private static int total_amt=0;
    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        this.setLocationRelativeTo(null);
        model= (DefaultTableModel)product_table.getModel();
        model.setRowCount(0);
       
    }
    public static void setSelectedItem(String name){
       cust_name_txt.setText(name);
       cust_name = name;
    }
    public static void setSelectedProduct(String name,String qty){
        //write sql code for inserting order table
        //in table data should be updated
        //i have give a label for (total_value_lable) here u update total ammount
        //while submit btn pressed dailog box with orderd!!
        Date d = order_date.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date = df.format(d);//date value
        String product_id=null;
        String cust_id=null;
        int p_cost=0;
        try{
            Connection con = SQL_Ops.getConnection();
            ResultSet rs2 = SQL_Ops.getCustID(cust_name);
            ResultSet rs1 = SQL_Ops.getProduct_ID(name);
            ResultSet rs = SQL_Ops.getP_Cost(name);
            rs2.next();
            rs1.next();
            rs.next();
            product_id = rs1.getString(1);
            cust_id=rs2.getString(1);
            p_cost = rs.getInt(1);
            //cust_id_label.setText(cust_id);
            System.out.println(cust_id);
        }
        catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error");
        }
        String order="INSERT INTO ORDERS VALUES('"+order_id_txt.getText()+"','"+date+"',"+p_cost+",'"+cust_id+"','"+product_id+"',"+qty+")";
        SQL_Ops.UpdateTable(order);
        int amount = p_cost * Integer.parseInt(qty);
        total_amt = total_amt+amount;
        total_value_label.setText(total_amt+" Rs");
        Object[] obj = {++si,name,p_cost,qty,amount};
        model.addRow(obj);
        product_table.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cust_name_txt = new javax.swing.JTextField();
        cust_id_label = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        order_date = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        products_label = new javax.swing.JLabel();
        order_id_txt = new javax.swing.JTextField();
        add_products_btn = new javax.swing.JButton();
        total_value_label = new javax.swing.JLabel();
        order_id_label2 = new javax.swing.JLabel();
        remove_products_btn = new javax.swing.JButton();
        remove_products_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        add_products_label1 = new javax.swing.JLabel();
        total_label1 = new javax.swing.JLabel();
        order_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 122, 231));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 620));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing-fill.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Home");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("2019  CSSM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/copyright1.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("BILLING");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));
        jPanel1.add(cust_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 140, -1));

        cust_id_label.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cust_id_label.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(cust_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        order_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_dateActionPerformed(evt);
            }
        });
        jPanel1.add(order_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(31, 122, 231));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pick Customer");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, 30));

        products_label.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        products_label.setForeground(new java.awt.Color(254, 254, 254));
        products_label.setText("Products:");
        jPanel1.add(products_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(order_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        add_products_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_white_fill.png"))); // NOI18N
        add_products_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add_products_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_products_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_products_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        total_value_label.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        total_value_label.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(total_value_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        order_id_label2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        order_id_label2.setForeground(new java.awt.Color(254, 254, 254));
        order_id_label2.setText("Order Id:");
        jPanel1.add(order_id_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        remove_products_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_white_fill.png"))); // NOI18N
        remove_products_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        remove_products_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_products_btnActionPerformed(evt);
            }
        });
        jPanel1.add(remove_products_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        remove_products_label.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        remove_products_label.setForeground(new java.awt.Color(254, 254, 254));
        remove_products_label.setText("Remove Product");
        jPanel1.add(remove_products_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "SI", "Product", "Rate", "Qty","Amount(Rs)"
            }
        ));
        product_table.setRowHeight(15);
        jScrollPane1.setViewportView(product_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 150));

        add_products_label1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        add_products_label1.setForeground(new java.awt.Color(254, 254, 254));
        add_products_label1.setText("Add Product");
        jPanel1.add(add_products_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        total_label1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        total_label1.setForeground(new java.awt.Color(254, 254, 254));
        total_label1.setText("Total:");
        jPanel1.add(total_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        order_btn.setBackground(new java.awt.Color(255, 255, 255));
        order_btn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        order_btn.setForeground(new java.awt.Color(31, 122, 231));
        order_btn.setText("Order");
        order_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btnActionPerformed(evt);
            }
        });
        jPanel1.add(order_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 70, 40));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Cutomer name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        EmpHome.main(null);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void order_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_dateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pick_customer.main(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_products_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_products_btnActionPerformed
        Pick_products.main(null);
    }//GEN-LAST:event_add_products_btnActionPerformed

    private void remove_products_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_products_btnActionPerformed
      if(product_table.getSelectedRowCount()==0){
          JOptionPane.showMessageDialog(this,"please select to delete!!");
      }
      else{
            int row = product_table.getSelectedRow();
            String date=null,p_id=null;
            int qantity;
            Date d = Calendar.getInstance().getTime();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            date = df.format(d);

            qantity = Integer.parseInt(product_table.getModel().getValueAt(row,3).toString());
            String p_name = product_table.getModel().getValueAt(row,1).toString();
            try{
              ResultSet rs = SQL_Ops.getProduct_ID(p_name);
              rs.next();
              p_id = rs.getString(1);
            }
            catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error");
            }
            SQL_Ops.delete_ordered_products(date, p_id, qantity);
            int amt = Integer.valueOf(product_table.getModel().getValueAt(row, 4).toString());
            model.removeRow(row);
            product_table.setModel(model);
            si=si-1;
            for(int j=1;j<=si;j++){
               product_table.getModel().setValueAt(String.valueOf(j),j-1,0);
            }
            product_table.setModel(model);
            total_amt = total_amt - amt;
            total_value_label.setText(String.valueOf(total_amt));
        }
    }//GEN-LAST:event_remove_products_btnActionPerformed

    private void order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btnActionPerformed
       JOptionPane.showMessageDialog(this,"Ordered Successfully!!");
       cust_name_txt.setText("");
       order_id_txt.setText("");
    }//GEN-LAST:event_order_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_products_btn;
    private javax.swing.JLabel add_products_label1;
    private javax.swing.JButton back_btn;
    private static javax.swing.JLabel cust_id_label;
    private static javax.swing.JTextField cust_name_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton order_btn;
    private static org.jdesktop.swingx.JXDatePicker order_date;
    private javax.swing.JLabel order_id_label2;
    private static javax.swing.JTextField order_id_txt;
    private static javax.swing.JTable product_table;
    private javax.swing.JLabel products_label;
    private javax.swing.JButton remove_products_btn;
    private javax.swing.JLabel remove_products_label;
    private javax.swing.JLabel total_label1;
    private static javax.swing.JLabel total_value_label;
    // End of variables declaration//GEN-END:variables
}
