/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rajeshwari
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        user_label = new javax.swing.JLabel();
        username_txt = new org.jdesktop.swingx.JXTextField();
        user_label1 = new javax.swing.JLabel();
        username_txt1 = new org.jdesktop.swingx.JXTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Profile");

        jPanel1.setBackground(new java.awt.Color(31, 122, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Home");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_label.setForeground(new java.awt.Color(60, 68, 69));
        user_label.setText("Current username......");
        jPanel2.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        username_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        username_txt.setForeground(new java.awt.Color(60, 68, 69));
        username_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        username_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_txtKeyTyped(evt);
            }
        });
        jPanel2.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 40));

        user_label1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_label1.setForeground(new java.awt.Color(60, 68, 69));
        user_label1.setText("New username......");
        jPanel2.add(user_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        username_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        username_txt1.setForeground(new java.awt.Color(60, 68, 69));
        username_txt1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        username_txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_txt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_txt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_txt1KeyTyped(evt);
            }
        });
        jPanel2.add(username_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, 40));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Change");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jButton2.setBackground(new java.awt.Color(31, 122, 231));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rounded_btn_new.png"))); // NOI18N
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressed_new_btn_login.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 280, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void username_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            username_txt1.requestFocus();
        }
    }//GEN-LAST:event_username_txtKeyPressed

    private void username_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyReleased
        if((username_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current username......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_username_txtKeyReleased

    private void username_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyTyped
        if((username_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current username......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_username_txtKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(username_txt.getText().equals("") || username_txt1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter all the fields");
        }else{
            JOptionPane.showMessageDialog(this,"Signed up succesfully!!");
            username_txt.setText("");
            username_txt1.setText("");
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label1.setEnabled(true);
            user_label1.setVisible(true);
            username_txt.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void username_txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txt1KeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(username_txt.getText().equals("") || username_txt1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter all the fields");
        }else{
            JOptionPane.showMessageDialog(this,"Changed username succesfully!!");
             username_txt.setText("");
             username_txt1.setText("");
             user_label.setEnabled(true);
             user_label.setVisible(true);
             user_label1.setEnabled(true);
             user_label1.setVisible(true);
             username_txt.requestFocus();
        }
        }
    }//GEN-LAST:event_username_txt1KeyPressed

    private void username_txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txt1KeyReleased
         if((username_txt1.getText()).equals("")){
            user_label1.setEnabled(true);
            user_label1.setVisible(true);
            user_label1.setText("New username......");
        }else{
            user_label1.setVisible(false);
            user_label1.setEnabled(false);
        }
    }//GEN-LAST:event_username_txt1KeyReleased

    private void username_txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txt1KeyTyped
        if((username_txt1.getText()).equals("")){
            user_label1.setEnabled(true);
            user_label1.setVisible(true);
            user_label1.setText("New username......");
        }else{
            user_label1.setVisible(false);
            user_label1.setEnabled(false);
        }
    }//GEN-LAST:event_username_txt1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel user_label;
    private javax.swing.JLabel user_label1;
    private org.jdesktop.swingx.JXTextField username_txt;
    private org.jdesktop.swingx.JXTextField username_txt1;
    // End of variables declaration//GEN-END:variables
}
