/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rajeshwari
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        confirm_pass_label = new javax.swing.JLabel();
        user_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        change_pass_btn = new javax.swing.JButton();
        username_txt = new org.jdesktop.swingx.JXTextField();
        confirm_pass_txt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");

        jPanel1.setBackground(new java.awt.Color(31, 122, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirm_pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_label.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_label.setText("Confirm password......");
        jPanel3.add(confirm_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        user_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_label.setForeground(new java.awt.Color(60, 68, 69));
        user_label.setText("Current username......");
        jPanel3.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pass_label.setForeground(new java.awt.Color(60, 68, 69));
        pass_label.setText("New password......");
        jPanel3.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        password_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password_txt.setForeground(new java.awt.Color(60, 68, 69));
        password_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        password_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_txtKeyTyped(evt);
            }
        });
        jPanel3.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 220, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Change");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        change_pass_btn.setBackground(new java.awt.Color(31, 122, 231));
        change_pass_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rounded_btn_new.png"))); // NOI18N
        change_pass_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressed_new_btn_login.png"))); // NOI18N
        change_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pass_btnActionPerformed(evt);
            }
        });
        jPanel3.add(change_pass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, 40));

        username_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        username_txt.setForeground(new java.awt.Color(60, 68, 69));
        username_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        username_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_txtKeyTyped(evt);
            }
        });
        jPanel3.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 40));

        confirm_pass_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_txt.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        confirm_pass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyTyped(evt);
            }
        });
        jPanel3.add(confirm_pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void password_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            confirm_pass_txt.requestFocus();
        }
    }//GEN-LAST:event_password_txtKeyPressed

    private void password_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyReleased
        if((password_txt.getText()).equals("")){
            pass_label.setEnabled(true);
            pass_label.setVisible(true);
            pass_label.setText("New password......");
        }else{
            pass_label.setVisible(false);
            pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txtKeyReleased

    private void password_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyTyped
        if((password_txt.getText()).equals("")){
            pass_label.setEnabled(true);
            pass_label.setVisible(true);
            pass_label.setText("New password......");
        }else{
            pass_label.setVisible(false);
            pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txtKeyTyped

    private void change_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pass_btnActionPerformed
        if(username_txt.getText().equals("") || password_txt.getText().equals("") || confirm_pass_txt.getText().equals(""))
            JOptionPane.showMessageDialog(this,"please enter all the fields!!");
        else if(!password_txt.getText().equals(confirm_pass_txt.getText())){            
            JOptionPane.showMessageDialog(this,"The password does't match!");
        }
        else{
                SQL_Ops.forgotPass(confirm_pass_txt.getText(), username_txt.getText());
                username_txt.setText("");
                password_txt.setText("");
                confirm_pass_txt.setText("");
                user_label.setVisible(true);
                pass_label.setVisible(true);
                user_label.setEnabled(true);
                pass_label.setEnabled(true);
                confirm_pass_label.setEnabled(true);
                confirm_pass_label.setVisible(true);
            }
    }//GEN-LAST:event_change_pass_btnActionPerformed

    private void username_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            password_txt.requestFocus();
        }
    }//GEN-LAST:event_username_txtKeyPressed

    private void username_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyReleased
        if((username_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current username......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_username_txtKeyReleased

    private void username_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyTyped
        if((username_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current username......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_username_txtKeyTyped

    private void confirm_pass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        if(username_txt.getText().equals("") || password_txt.getText().equals("") || confirm_pass_txt.getText().equals(""))
            JOptionPane.showMessageDialog(this,"please enter all the fields!!");
        else if(!password_txt.getText().equals(confirm_pass_txt.getText())){
            JOptionPane.showMessageDialog(this,"The password does't match!");
        }
        else{
                JOptionPane.showMessageDialog(this,"password changed Successfully!!");
                username_txt.setText("");
                password_txt.setText("");
                confirm_pass_txt.setText("");
                user_label.setVisible(true);
                pass_label.setVisible(true);
                user_label.setEnabled(true);
                pass_label.setEnabled(true);
                confirm_pass_label.setEnabled(true);
                confirm_pass_label.setVisible(true);
            }
        }
    }//GEN-LAST:event_confirm_pass_txtKeyPressed

    private void confirm_pass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyReleased
        if((confirm_pass_txt.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_confirm_pass_txtKeyReleased

    private void confirm_pass_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyTyped
        if((confirm_pass_txt.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_confirm_pass_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton change_pass_btn;
    private javax.swing.JLabel confirm_pass_label;
    private javax.swing.JPasswordField confirm_pass_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pass_label;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JLabel user_label;
    private org.jdesktop.swingx.JXTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
