/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author rajeshwari
 */
public class Pick_products extends javax.swing.JFrame {
private String product_name = null;
    /**
     * Creates new form Pick_customer
     */
    public Pick_products() {
        initComponents();
        this.bindData();
        this.setLocationRelativeTo(null);
        product_list.setVisible(false);
        jScrollPane1.setVisible(false);
    }
    public String getSelectedItem(){
        return product_name;
    }
    DefaultListModel dm = new DefaultListModel();
    
    private static ArrayList getData(){
        ArrayList product = new ArrayList();
        try{
            Connection con = SQL_Ops.getConnection();
            Statement stmt = con.createStatement();
            String sql = "select P_Name from PRODUCTS;";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                product.add(rs.getString(1));
            }
        }catch(Exception e){};
        return product;
    }
    private void bindData(){
        getData().stream().forEach((product)->{
           dm.addElement(product);
        });
        product_list.setModel(dm);
        product_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    private void serachFilter(String searchTerm){
        DefaultListModel fi = new DefaultListModel();
        ArrayList prodfill = getData();
        prodfill.stream().forEach((product)->{
            String product_name = product.toString().toLowerCase();
            if(product_name.contains(searchTerm.toLowerCase())){
                fi.addElement(product);
            }
       });
        dm=fi;
        product_list.setModel(dm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        search_text = new javax.swing.JLabel();
        product_txt = new javax.swing.JTextField();
        add_bnt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_list = new javax.swing.JList<>();
        product_label = new javax.swing.JLabel();
        product_select_txt = new javax.swing.JTextField();
        order_id_label2 = new javax.swing.JLabel();
        qty_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pick products");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 122, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/serch_btn.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        search_text.setText("Search Products......");
        jPanel1.add(search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        product_txt.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        product_txt.setToolTipText("");
        product_txt.setBorder(null);
        product_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        product_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_txtMouseClicked(evt);
            }
        });
        product_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_txtActionPerformed(evt);
            }
        });
        product_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                product_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                product_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                product_txtKeyTyped(evt);
            }
        });
        jPanel1.add(product_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 40));

        add_bnt.setBackground(new java.awt.Color(31, 122, 231));
        add_bnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_btn.png"))); // NOI18N
        add_bnt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add_bnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bntActionPerformed(evt);
            }
        });
        jPanel1.add(add_bnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_btn.png"))); // NOI18N
        jButton3.setBorder(null);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Delete");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Billing");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        product_list.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        product_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        product_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(product_list);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 270, 150));

        product_label.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        product_label.setForeground(new java.awt.Color(254, 254, 254));
        product_label.setText("product:");
        jPanel1.add(product_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel1.add(product_select_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, -1));

        order_id_label2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        order_id_label2.setForeground(new java.awt.Color(254, 254, 254));
        order_id_label2.setText("Qty:");
        jPanel1.add(order_id_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        jPanel1.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_txtMouseClicked

    }//GEN-LAST:event_product_txtMouseClicked

    private void product_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_txtActionPerformed
       
    }//GEN-LAST:event_product_txtActionPerformed

    private void product_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            
       }
    }//GEN-LAST:event_product_txtKeyPressed

    private void product_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_txtKeyReleased
        if((product_txt.getText()).equals("")){
            search_text.setEnabled(true);
            search_text.setVisible(true);
            search_text.setText("Search Products......");
        }else{
            search_text.setVisible(false);
            search_text.setEnabled(false);
        }
        serachFilter(product_txt.getText());
         product_list.setVisible(true);
         jScrollPane1.setVisible(true);
    }//GEN-LAST:event_product_txtKeyReleased

    private void product_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_txtKeyTyped
        if((product_txt.getText()).equals("")){
            search_text.setEnabled(true);
            search_text.setVisible(true);
            search_text.setText("Search Products......");
        }else{
            search_text.setVisible(false);
            search_text.setEnabled(false);
        }
    }//GEN-LAST:event_product_txtKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void product_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_listMouseClicked
       product_name = product_list.getSelectedValue();
       product_select_txt.setText(product_name);
       product_list.setVisible(false);
       jScrollPane1.setVisible(false);
       product_txt.setText("");
        if((product_txt.getText()).equals("")){
            search_text.setEnabled(true);
            search_text.setVisible(true);
            search_text.setText("Search Products......");
        }else{
            search_text.setVisible(false);
            search_text.setEnabled(false);
        }
    }//GEN-LAST:event_product_listMouseClicked

    private void add_bntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bntActionPerformed
        Billing.setSelectedProduct(product_name,qty_txt.getText());
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_add_bntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pick_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pick_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pick_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pick_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pick_products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_bnt;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel order_id_label2;
    private javax.swing.JLabel product_label;
    private javax.swing.JList<String> product_list;
    private static javax.swing.JTextField product_select_txt;
    private javax.swing.JTextField product_txt;
    private static javax.swing.JTextField qty_txt;
    private javax.swing.JLabel search_text;
    // End of variables declaration//GEN-END:variables
}
