/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author rajeshwari
 */
public class Pick_customer extends javax.swing.JFrame {
private String cust_name = null;
    /**
     * Creates new form Pick_customer
     */
    public Pick_customer() {
        initComponents();
        this.bindData();
        this.setLocationRelativeTo(null);
    }
    public String getSelectedItem(){
        return cust_name;
    }
    DefaultListModel dm = new DefaultListModel();
    
    private static ArrayList getData(){
        ArrayList cust = new ArrayList();
        try{
            Connection con = SQL_Ops.getConnection();
            Statement stmt = con.createStatement();
            String sql = "SELECT Cust_Name FROM CUSTOMER;";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                cust.add(rs.getString(1));
            }
        }catch(Exception e){};
        return cust;
    }
    private void bindData(){
        getData().stream().forEach((cust)->{
           dm.addElement(cust);
        });
        customer_list.setModel(dm);
        customer_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    private void serachFilter(String searchTerm){
        DefaultListModel fi = new DefaultListModel();
        ArrayList custfil = getData();
        custfil.stream().forEach((cust)->{
            String cust_name = cust.toString().toLowerCase();
            if(cust_name.contains(searchTerm.toLowerCase())){
                fi.addElement(cust);
            }
       });
        dm=fi;
        customer_list.setModel(dm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        search_text = new javax.swing.JLabel();
        cust_txt = new javax.swing.JTextField();
        add_bnt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        add_customer_label = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer_list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pick Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 122, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/serch_btn.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        search_text.setText("Search Customers......");
        jPanel1.add(search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        cust_txt.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cust_txt.setToolTipText("");
        cust_txt.setBorder(null);
        cust_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_txtMouseClicked(evt);
            }
        });
        cust_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_txtActionPerformed(evt);
            }
        });
        cust_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cust_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cust_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cust_txtKeyTyped(evt);
            }
        });
        jPanel1.add(cust_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 40));

        add_bnt.setBackground(new java.awt.Color(31, 122, 231));
        add_bnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_btn.png"))); // NOI18N
        add_bnt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add_bnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bntActionPerformed(evt);
            }
        });
        jPanel1.add(add_bnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        add_customer_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        add_customer_label.setForeground(new java.awt.Color(255, 255, 255));
        add_customer_label.setText("Add Customer");
        add_customer_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_customer_labelMouseClicked(evt);
            }
        });
        jPanel1.add(add_customer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Billing");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        customer_list.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        customer_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        customer_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customer_list);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 40, 280, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cust_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_txtMouseClicked

    }//GEN-LAST:event_cust_txtMouseClicked

    private void cust_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_txtActionPerformed

    }//GEN-LAST:event_cust_txtActionPerformed

    private void cust_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_txtKeyPressed

    }//GEN-LAST:event_cust_txtKeyPressed

    private void cust_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_txtKeyReleased
        if((cust_txt.getText()).equals("")){
            search_text.setEnabled(true);
            search_text.setVisible(true);
            search_text.setText("Search Customers......");
        }else{
            search_text.setVisible(false);
            search_text.setEnabled(false);
        }
        serachFilter(cust_txt.getText());
    }//GEN-LAST:event_cust_txtKeyReleased

    private void cust_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_txtKeyTyped
        if((cust_txt.getText()).equals("")){
            search_text.setEnabled(true);
            search_text.setVisible(true);
            search_text.setText("Search Customers......");
        }else{
            search_text.setVisible(false);
            search_text.setEnabled(false);
        }
    }//GEN-LAST:event_cust_txtKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void add_customer_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_customer_labelMouseClicked
        add_customer_label.setForeground(new Color(255,104,31));
        Customers.main(null);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_add_customer_labelMouseClicked

    private void customer_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_listMouseClicked
       cust_name = customer_list.getSelectedValue();
    }//GEN-LAST:event_customer_listMouseClicked

    private void add_bntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bntActionPerformed
        Billing.setSelectedItem(cust_name);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_add_bntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pick_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pick_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pick_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pick_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pick_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_bnt;
    private javax.swing.JLabel add_customer_label;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField cust_txt;
    private javax.swing.JList<String> customer_list;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel search_text;
    // End of variables declaration//GEN-END:variables
}
