/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rajeshwari
 */
public class Settings_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings_Admin() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        settings_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        setting_option = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        pass_label = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        change_pass_btn = new javax.swing.JButton();
        user_label = new javax.swing.JLabel();
        user_txt = new javax.swing.JPasswordField();
        confirm_pass_label = new javax.swing.JLabel();
        confirm_pass_txt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 122, 231));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Home");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        settings_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings1.png"))); // NOI18N
        settings_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        settings_btn.setBorderPainted(false);
        settings_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_btnActionPerformed(evt);
            }
        });
        jPanel2.add(settings_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Settings");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 26, -1, -1));

        setting_option.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        setting_option.setForeground(new java.awt.Color(31, 122, 231));
        setting_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Change password"}));
        setting_option.setToolTipText("");
        setting_option.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setting_option.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setting_optionItemStateChanged(evt);
            }
        });
        setting_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setting_optionActionPerformed(evt);
            }
        });
        jPanel2.add(setting_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 18, 116, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pass_label.setForeground(new java.awt.Color(60, 68, 69));
        pass_label.setText("New password......");
        jPanel1.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        password_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password_txt.setForeground(new java.awt.Color(60, 68, 69));
        password_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        password_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_txtKeyTyped(evt);
            }
        });
        jPanel1.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Change");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        change_pass_btn.setBackground(new java.awt.Color(31, 122, 231));
        change_pass_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rounded_btn_new.png"))); // NOI18N
        change_pass_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressed_new_btn_login.png"))); // NOI18N
        change_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pass_btnActionPerformed(evt);
            }
        });
        jPanel1.add(change_pass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 40));

        user_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_label.setForeground(new java.awt.Color(60, 68, 69));
        user_label.setText("Current password......");
        jPanel1.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        user_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_txt.setForeground(new java.awt.Color(60, 68, 69));
        user_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        user_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_txtActionPerformed(evt);
            }
        });
        user_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user_txtKeyTyped(evt);
            }
        });
        jPanel1.add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        confirm_pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_label.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_label.setText("Confirm password......");
        jPanel1.add(confirm_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        confirm_pass_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_txt.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        confirm_pass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyTyped(evt);
            }
        });
        jPanel1.add(confirm_pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 290, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settings_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settings_btnActionPerformed

    private void setting_optionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setting_optionItemStateChanged
       
    }//GEN-LAST:event_setting_optionItemStateChanged

    private void setting_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setting_optionActionPerformed
        if(setting_option.getSelectedItem().equals("Change password")){
            jPanel1.setVisible(true);
        }
    }//GEN-LAST:event_setting_optionActionPerformed

    private void password_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           confirm_pass_txt.requestFocus();
        }
    }//GEN-LAST:event_password_txtKeyPressed

    private void password_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyReleased
        if((password_txt.getText()).equals("")){
            pass_label.setEnabled(true);
            pass_label.setVisible(true);
            pass_label.setText("New password......");
        }else{
            pass_label.setVisible(false);
            pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txtKeyReleased

    private void password_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyTyped
        if((password_txt.getText()).equals("")){
            pass_label.setEnabled(true);
            pass_label.setVisible(true);
            pass_label.setText("New password......");
        }else{
            pass_label.setVisible(false);
            pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txtKeyTyped

    private void change_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pass_btnActionPerformed
       if(user_txt.getText().equals("") || password_txt.getText().equals("") || confirm_pass_txt.getText().equals(""))
                JOptionPane.showMessageDialog(this,"please enter all the fields!!");
            else if(!password_txt.getText().equals(confirm_pass_txt.getText())){
                JOptionPane.showMessageDialog(this,"password doesnt match!!");
            }
            else{
            JOptionPane.showMessageDialog(this,"password changed Successfully!!");
            user_txt.setText("");
             password_txt.setText("");
             confirm_pass_txt.setText("");
             user_label.setVisible(true);
             pass_label.setVisible(true);
             user_label.setEnabled(true);
             pass_label.setEnabled(true);
             confirm_pass_label.setEnabled(true);
             confirm_pass_label.setVisible(true);
            }
    }//GEN-LAST:event_change_pass_btnActionPerformed

    private void user_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_txtKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            password_txt.requestFocus();
        }
    }//GEN-LAST:event_user_txtKeyPressed

    private void user_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_txtKeyReleased
         if((user_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current password......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_user_txtKeyReleased

    private void user_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_txtKeyTyped
       if((user_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current password......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_user_txtKeyTyped

    private void user_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_txtActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void confirm_pass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(user_txt.getText().equals("") || password_txt.getText().equals("")|| confirm_pass_txt.getText().equals(""))
                JOptionPane.showMessageDialog(this,"please enter all the fields!!");
            else if(!password_txt.getText().equals(confirm_pass_txt.getText())){
                JOptionPane.showMessageDialog(this,"password doesnt match!!");
            }
            else{
            JOptionPane.showMessageDialog(this,"password changed Successfully!!");
            user_txt.setText("");
             password_txt.setText("");
             confirm_pass_txt.setText("");
             user_label.setVisible(true);
             pass_label.setVisible(true);
             user_label.setEnabled(true);
             pass_label.setEnabled(true);
             confirm_pass_label.setEnabled(true);
             confirm_pass_label.setVisible(true);
            }
        }
    }//GEN-LAST:event_confirm_pass_txtKeyPressed

    private void confirm_pass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyReleased
       if((confirm_pass_txt.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_confirm_pass_txtKeyReleased

    private void confirm_pass_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyTyped
        if((confirm_pass_txt.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_confirm_pass_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton change_pass_btn;
    private javax.swing.JLabel confirm_pass_label;
    private javax.swing.JPasswordField confirm_pass_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pass_label;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JComboBox<String> setting_option;
    private javax.swing.JButton settings_btn;
    private javax.swing.JLabel user_label;
    private javax.swing.JPasswordField user_txt;
    // End of variables declaration//GEN-END:variables
}
