/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rajeshwari
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    static String emp_ID;
    public static void getEmpID(String emp_ID){
        Settings.emp_ID=emp_ID;
    }
    
    public Settings() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        settings_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        setting_option = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        pass_label = new javax.swing.JLabel();
        password_txt1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        change_pass_btn = new javax.swing.JButton();
        user_label = new javax.swing.JLabel();
        old_Pass = new javax.swing.JPasswordField();
        confirm_pass_label = new javax.swing.JLabel();
        password_txt2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 122, 231));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Home");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        settings_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings1.png"))); // NOI18N
        settings_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        settings_btn.setBorderPainted(false);
        settings_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_btnActionPerformed(evt);
            }
        });
        jPanel2.add(settings_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Settings");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 26, -1, -1));

        setting_option.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        setting_option.setForeground(new java.awt.Color(31, 122, 231));
        setting_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Change password"}));
        setting_option.setToolTipText("");
        setting_option.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setting_option.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setting_optionItemStateChanged(evt);
            }
        });
        setting_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setting_optionActionPerformed(evt);
            }
        });
        jPanel2.add(setting_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 18, 116, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pass_label.setForeground(new java.awt.Color(60, 68, 69));
        pass_label.setText("New password......");
        jPanel1.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        password_txt1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password_txt1.setForeground(new java.awt.Color(60, 68, 69));
        password_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        password_txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_txt1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_txt1KeyReleased(evt);
            }
        });
        jPanel1.add(password_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Change");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        change_pass_btn.setBackground(new java.awt.Color(31, 122, 231));
        change_pass_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rounded_btn_new.png"))); // NOI18N
        change_pass_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressed_new_btn_login.png"))); // NOI18N
        change_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pass_btnActionPerformed(evt);
            }
        });
        jPanel1.add(change_pass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 40));

        user_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_label.setForeground(new java.awt.Color(60, 68, 69));
        user_label.setText("Current password......");
        jPanel1.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        old_Pass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        old_Pass.setForeground(new java.awt.Color(60, 68, 69));
        old_Pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        old_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_PassActionPerformed(evt);
            }
        });
        old_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                old_PassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                old_PassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                old_PassKeyTyped(evt);
            }
        });
        jPanel1.add(old_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        confirm_pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_label.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_label.setText("Confirm password......");
        jPanel1.add(confirm_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        password_txt2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password_txt2.setForeground(new java.awt.Color(60, 68, 69));
        password_txt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        password_txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_txt2KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txt2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_txt2KeyReleased(evt);
            }
        });
        jPanel1.add(password_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 290, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settings_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settings_btnActionPerformed

    private void setting_optionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setting_optionItemStateChanged
       
    }//GEN-LAST:event_setting_optionItemStateChanged

    private void setting_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setting_optionActionPerformed
        if(setting_option.getSelectedItem().equals("Change password")){
            jPanel1.setVisible(true);
        }
    }//GEN-LAST:event_setting_optionActionPerformed

    private void password_txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt1KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           password_txt2.requestFocus();
        }
    }//GEN-LAST:event_password_txt1KeyPressed

    private void password_txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt1KeyReleased
        if((password_txt1.getText()).equals("")){
            pass_label.setEnabled(true);
            pass_label.setVisible(true);
            pass_label.setText("New password......");
        }else{
            pass_label.setVisible(false);
            pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txt1KeyReleased

    private void password_txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt1KeyTyped
        if((password_txt1.getText()).equals("")){
            pass_label.setEnabled(true);
            pass_label.setVisible(true);
            pass_label.setText("New password......");
        }else{
            pass_label.setVisible(false);
            pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txt1KeyTyped

    private void change_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pass_btnActionPerformed
       if(old_Pass.getText().equals("") || password_txt1.getText().equals("") || password_txt2.getText().equals(""))
                JOptionPane.showMessageDialog(this,"Please Enter All the Fields!!");
      else{
            String SQL="SELECT Password FROM EMP_LOGIN WHERE Emp_ID='"+emp_ID+"'";
            String checkOldPass=SQL_Ops.getPassword(SQL);
            if(checkOldPass.equals(old_Pass.getText())){
                if(password_txt1.getText().equals(password_txt2.getText())){
                    String SQL2="UPDATE EMP_LOGIN SET Password='"+password_txt2.getText()+"' WHERE Emp_ID='"+emp_ID+"'";
                    SQL_Ops.changePass(SQL2);
                }
                else{
                    JOptionPane.showMessageDialog(null, "New passwords do not match");
                    password_txt1.setText("");
                    password_txt2.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Provided old password is incorrect");
                old_Pass.setText("");
                password_txt1.setText("");
                password_txt2.setText("");
        
            }
            //JOptionPane.showMessageDialog(this,"password changed Successfully!!");
            this.dispose();
            /*old_Pass.setText("");
            password_txt1.setText("");
            user_label.setVisible(true);
            pass_label.setVisible(true);
            user_label.setEnabled(true);
            pass_label.setEnabled(true);*/
            }
    }//GEN-LAST:event_change_pass_btnActionPerformed

    private void old_PassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_old_PassKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            password_txt1.requestFocus();
        }
    }//GEN-LAST:event_old_PassKeyPressed

    private void old_PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_old_PassKeyReleased
         if((old_Pass.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current password......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_old_PassKeyReleased

    private void old_PassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_old_PassKeyTyped
       if((old_Pass.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Current password......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_old_PassKeyTyped

    private void old_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_old_PassActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void password_txt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt2KeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(old_Pass.getText().equals("") || password_txt1.getText().equals("")|| password_txt2.getText().equals(""))
                JOptionPane.showMessageDialog(this,"please enter all the fields!!");
            else if(!password_txt1.getText().equals(password_txt2.getText())){
                JOptionPane.showMessageDialog(this,"password doesnt match!!");
            }
            else{
            JOptionPane.showMessageDialog(this,"password changed Successfully!!");
            old_Pass.setText("");
             password_txt1.setText("");
             password_txt2.setText("");
             user_label.setVisible(true);
             pass_label.setVisible(true);
             user_label.setEnabled(true);
             pass_label.setEnabled(true);
             confirm_pass_label.setEnabled(true);
             confirm_pass_label.setVisible(true);
            }
        }
    }//GEN-LAST:event_password_txt2KeyPressed

    private void password_txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt2KeyReleased
       if((password_txt2.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txt2KeyReleased

    private void password_txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt2KeyTyped
        if((password_txt2.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_password_txt2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton change_pass_btn;
    private javax.swing.JLabel confirm_pass_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField old_Pass;
    private javax.swing.JLabel pass_label;
    private javax.swing.JPasswordField password_txt1;
    private javax.swing.JPasswordField password_txt2;
    private javax.swing.JComboBox<String> setting_option;
    private javax.swing.JButton settings_btn;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
