/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssmp;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rajeshwari
 */
public class signup_Emp extends javax.swing.JFrame {

    /**
     * Creates new form signup_Emp
     */
    public signup_Emp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        user_label = new javax.swing.JLabel();
        username_txt = new org.jdesktop.swingx.JXTextField();
        confirm_pass_label = new javax.swing.JLabel();
        confirm_pass_txt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pass_label1 = new javax.swing.JLabel();
        password_txt1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee SignUp");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 122, 231));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        user_label.setForeground(new java.awt.Color(60, 68, 69));
        user_label.setText("Enter username......");
        jPanel2.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        username_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        username_txt.setForeground(new java.awt.Color(60, 68, 69));
        username_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        username_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_txtKeyTyped(evt);
            }
        });
        jPanel2.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 220, 40));

        confirm_pass_label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_label.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_label.setText("Confirm password......");
        jPanel2.add(confirm_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        confirm_pass_txt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm_pass_txt.setForeground(new java.awt.Color(60, 68, 69));
        confirm_pass_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        confirm_pass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirm_pass_txtKeyTyped(evt);
            }
        });
        jPanel2.add(confirm_pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 220, 40));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Signup");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jButton2.setBackground(new java.awt.Color(31, 122, 231));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rounded_btn_new.png"))); // NOI18N
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressed_new_btn_login.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, 40));

        pass_label1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pass_label1.setForeground(new java.awt.Color(60, 68, 69));
        pass_label1.setText("Enter password......");
        jPanel2.add(pass_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        password_txt1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password_txt1.setForeground(new java.awt.Color(60, 68, 69));
        password_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 122, 231)));
        password_txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_txt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_txt1KeyTyped(evt);
            }
        });
        jPanel2.add(password_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 220, 40));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 122, 231));
        jLabel6.setText("Employee SignUp");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/computer_sales.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register Here>>");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to Cssm");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Back to Employee login page");

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_to_home.png"))); // NOI18N
        back_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back_btn)
                        .addGap(20, 20, 20))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            password_txt1.requestFocus();
        }
    }//GEN-LAST:event_username_txtKeyPressed

    private void username_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyReleased
        if((username_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Enter username......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_username_txtKeyReleased

    private void username_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyTyped
        if((username_txt.getText()).equals("")){
            user_label.setEnabled(true);
            user_label.setVisible(true);
            user_label.setText("Enter username......");
        }else{
            user_label.setVisible(false);
            user_label.setEnabled(false);
        }
    }//GEN-LAST:event_username_txtKeyTyped

    private void confirm_pass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(username_txt.getText().equals("") || password_txt1.getText().equals("") && confirm_pass_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Please enter all the fields");
            }else{
            JOptionPane.showMessageDialog(this,"Signed up succesfully!!");
            Login.main(null);
            this.dispose();
            this.setVisible(false);
            }
        }
    }//GEN-LAST:event_confirm_pass_txtKeyPressed

    private void confirm_pass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyReleased
        if((confirm_pass_txt.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_confirm_pass_txtKeyReleased

    private void confirm_pass_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_txtKeyTyped
        if((confirm_pass_txt.getText()).equals("")){
            confirm_pass_label.setEnabled(true);
            confirm_pass_label.setVisible(true);
            confirm_pass_label.setText("Confirm password......");
        }else{
            confirm_pass_label.setVisible(false);
            confirm_pass_label.setEnabled(false);
        }
    }//GEN-LAST:event_confirm_pass_txtKeyTyped

    private void password_txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt1KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            confirm_pass_txt.requestFocus();
        }
    }//GEN-LAST:event_password_txt1KeyPressed

    private void password_txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt1KeyReleased
        if((password_txt1.getText()).equals("")){
            pass_label1.setEnabled(true);
            pass_label1.setVisible(true);
            pass_label1.setText("Enter password......");
        }else{
            pass_label1.setVisible(false);
            pass_label1.setEnabled(false);
        }
    }//GEN-LAST:event_password_txt1KeyReleased

    private void password_txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txt1KeyTyped
        if((password_txt1.getText()).equals("")){
            pass_label1.setEnabled(true);
            pass_label1.setVisible(true);
            pass_label1.setText("Enter password......");
        }else{
            pass_label1.setVisible(false);
            pass_label1.setEnabled(false);
        }
    }//GEN-LAST:event_password_txt1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(username_txt.getText().equals("") || password_txt1.getText().equals("") && confirm_pass_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Please enter all the fields");
            }else{
        JOptionPane.showMessageDialog(this,"Signed up succesfully!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Login.main(null);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_Emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel confirm_pass_label;
    private javax.swing.JPasswordField confirm_pass_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pass_label1;
    private javax.swing.JPasswordField password_txt1;
    private javax.swing.JLabel user_label;
    private org.jdesktop.swingx.JXTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
